media: public/img
content:
  - name: posts
    label: Blog posts
    type: collection
    path: content/blog
    format: yaml-frontmatter
    fields:
      - name: title
        type: string
      - name: description
        type: text
      - name: date
        type: date
      - name: tags
        type: string
        list: true
      - name: body
        type: rich-text
    subfolders: true
    exclude: ["*.11tydata.js"]
  - name: pages
    label: Pages
    type: group
    items:   
      - name: home
        label: Home
        type: file
        path: content/index.njk
        fields:
          - name: title
            type: string
          - name: layout
            type: select
            options:
              values:
                - name: "layouts/base.njk"
                  label: Base
                - name: "layouts/home.njk"
                  label: Home
                - name: "layouts/post.njk"
                  label: Post
                - name: "layouts/project.njk"
                  label: Project
          - name: projectsToShow
            type: number
          - name: body
            type: rich-text
  - name: layouts
    label: Page Layouts
    type: collection
    path: _includes
    subfolders: true
    format: code